// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact            = require("reason-react/src/ReasonReact.js");
var PersonalInformationJsx = require("./PersonalInformation.jsx");

function make(name, children) {
  return ReasonReact.wrapJsForReason(PersonalInformationJsx.default, {
              name: name
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
