// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Js_boolean  = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactSlick  = require("react-slick");

function make(dots, infinite, speed, slidesToShow, slidesToScroll, children) {
  return ReasonReact.wrapJsForReason(ReactSlick, {
              dots: Js_boolean.to_js_boolean(dots),
              infinite: Js_boolean.to_js_boolean(infinite),
              speed: speed,
              slidesToShow: slidesToShow,
              slidesToScroll: slidesToScroll
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
